version: '2'
services:
  mariadb:
    build: ../mariadb.home
    hostname: mariadb
    volumes:
     - /share/mariadb/var/log:/var/log
     - /share/mariadb/var/lib/mysql:/var/lib/mysql
     - /var/tmp/ram:/var/tmp/ram
    restart: always
  maxscale:
    build: ../maxscale.home
    hostname: maxscale
    volumes:
     - /share/maxscale/var/log:/var/log
    links:
     - mariadb
    depends_on:
     - mariadb
    restart: always
  php-fpm:
    build: ../ubuntu/php-fpm.home
    hostname: php-fpm
    volumes:
     - /share/www/html:/var/www/html
    links:
     - mariadb
     - maxscale
    depends_on:
     - maxscale
     - mariadb
    restart: always
  memcached:
    build: ../alpine/memcached
    hostname: memcached
    restart: always
  nginx:
    build: ../ubuntu/nginx.home
    hostname: nginx
    volumes:
     - /share/nginx/var/log:/var/log
     - /share/www:/var/www
     - /share/letsencrypt:/etc/letsencrypt
    links:
     - php-fpm
     - memcached
    depends_on:
     - php-fpm
     - memcached
    ports:
     - "80:80"
     - "443:443"
    restart: always
